### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Ovyerus** [Sayo-nika/Junko#1]
Was asked to do review, here's some things.

app.ts
 - [L16](https://github.com/Sayo-nika/Junko/blob/ded19b6af3f6e28e67a244c9da44594eaa867048/src/app.ts#L16): might need to parse the env var as a number (`Number(env || default)`) as I believe Express complains if the port isn't a number.
 - [L17](https://github.com/Sayo-nika/Junko/blob/ded19b6af3f6e28e67a244c9da44594eaa867048/src/app.ts#L17): the `||` here won't do anything. Probably just load from the one config file, probably just `config.yml`.

models/post.ts
 - [L27](https://github.com/Sayo-nika/Junko/blob/ded19b6af3f6e28e67a244c9da44594eaa867048/src/models/post.ts#L27): second argument (`collection => PostCollection`), should be `collection => collection.images`, because TypeORM needs the second arguments to show the reverse side in relationships.

models/post-collection.ts
 - [L20](https://github.com/Sayo-nika/Junko/blob/ded19b6af3f6e28e67a244c9da44594eaa867048/src/models/post-collection.ts#L20): same as above, `post => Post` to `post => post.collections`.
 - [L21](https://github.com/Sayo-nika/Junko/blob/ded19b6af3f6e28e67a244c9da44594eaa867048/src/models/post-collection.ts#L21): maybe rename `images` to `posts`?

controllers/content-controller.ts
 - [L41](https://github.com/Sayo-nika/Junko/blob/ded19b6af3f6e28e67a244c9da44594eaa867048/src/controllers/content-controller.ts#L41): in newer versions of Node, `new Buffer(...)` emits a deprecation waning. Should probably use `Buffer.from(...)` which takes the exact same arguments.
 - [L42](https://github.com/Sayo-nika/Junko/blob/ded19b6af3f6e28e67a244c9da44594eaa867048/src/controllers/content-controller.ts#L42): from what I can see, owo.js doesn't support uploading of raw buffers, only files. (I think you're a contributor so you could probably add that functionality).

controllers/sagiri-controller.ts
 - [L21](https://github.com/Sayo-nika/Junko/blob/ded19b6af3f6e28e67a244c9da44594eaa867048/src/controllers/sagiri-controller.ts#L21): same Buffer stuff as above, `new Buffer(...)` to `Buffer.from(...)`.
 - [L22](https://github.com/Sayo-nika/Junko/blob/ded19b6af3f6e28e67a244c9da44594eaa867048/src/controllers/sagiri-controller.ts#L22): not sure why the `||` operator is being used here. Shouldn't it just be `rawBuffer`?

**Comment by sr229** [comment]
for L22: Frontend might do the passing of the `hostedURL` already so there's almost no need to reupload the same buffer to Sagiri's Controller.
